version: 2

project_name: bqls

builds:
  - id: bqls
    main: .
    binary: bqls
    ldflags:
      - -s -w -X main.version={{.Tag}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
  algorithm: sha256

changelog:
  use: github
